---
engines:
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.coffee"
exclude_paths:
- test/
- dist/
- docs/
- node_modules/
